### ISSUE TITLE
Please support edition 2021

### ISSUE THREAD

**Issue by linkdesu** [nervosnetwork/capsule#62]
Last week I tried to compile [rhai](https://github.com/rhaiscript/rhai) into our script, but one of its denpendecies named [smartstring](https://github.com/bodil/smartstring) requires edition 2021. 😓

[rhai](https://github.com/rhaiscript/rhai) seems to be a good choice for integrating some simple DSL into scripts, so I hope you guys could upgrade the docker image to support edition 2021 in the new future.

**Comment by TheWaWaR** [comment]
What's your currently docker image used? 

The latest capsule docker image is `thewawar/ckb-capsule:2021-12-25` and it was built from the `Dockerfile` in [current project](https://github.com/nervosnetwork/capsule/blob/7f78a78cf04f8b86f5e5ce143d7137a778200427/docker/Dockerfile#L4). You can see the rustc version is `nightly-2021-12-25`, since edition 2021 support from [stable rust 1.56.0](https://blog.rust-lang.org/2021/10/21/Rust-1.56.0.html), I think it's already supported in this docker image. You may change the `capsule.toml` config item [here](https://github.com/nervosnetwork/capsule/blob/7f78a78cf04f8b86f5e5ce143d7137a778200427/templates/capsule.toml#L6) to use that docker image.

NOTE: this docker image both support `arm64` and `x86_64`
