### ISSUE TITLE
Files in target are owned by root if building is interrupted

### ISSUE THREAD

**Issue by blckngm** [nervosnetwork/capsule#87]
We should run docker with `--user uid:gid` instead of `chown` after building.

**Comment by jjyr** [comment]
The rustup was installed with the root user, and using --user uid:gid can cause the docker container to be unable to find cargo.

Resolving this issue is harder than I anticipated. We have two ways to add users to the docker container:

Statically creating a user in the Dockerfile, but the uid and gid may not match the host's user, leading to potential permission issues.
Dynamically creating a user in the container, but this requires setting up the rust toolchain for the new user. This defeats the purpose of using docker to maintain the development environment.

Perhaps we should go straight with the `cross` instead docker. Can `cross` help us avoid this issue? #84

**Comment by blckngm** [comment]
Yeah cross doesn't seem to have this problem.

There are also complications involving rootless docker/podman, which cross seem to have handled.
